package com.restaurant.marketing.session;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.concurrent.ConcurrentHashMap;

/**
 * SessionStore — in-memory store for active conversations.
 *
 * Keyed by sessionId (generated by the frontend or controller).
 * Sessions expire after 30 minutes of inactivity and are cleaned
 * up automatically by the scheduled task.
 *
 * NOTE: This is in-memory only. If you restart the server, sessions
 * are lost. For production, swap this for Redis or a database.
 * The interface stays identical — just change this class.
 */
@Component
public class SessionStore {

    private static final Logger log = LoggerFactory.getLogger(SessionStore.class);
    private static final int SESSION_TIMEOUT_MINUTES = 30;

    private final ConcurrentHashMap<String, ConversationSession> sessions
            = new ConcurrentHashMap<>();

    /**
     * Get an existing session or create a new one.
     * Never returns null.
     */
    public ConversationSession getOrCreate(String sessionId) {
        return sessions.computeIfAbsent(sessionId, id -> {
            log.debug("Creating new session: {}", id);
            return new ConversationSession(id);
        });
    }

    /**
     * Get an existing session — returns null if not found.
     */
    public ConversationSession get(String sessionId) {
        return sessions.get(sessionId);
    }

    public int getActiveSessionCount() {
        return sessions.size();
    }

    /**
     * Clean up expired sessions every 10 minutes.
     * Prevents memory leaks from abandoned conversations.
     */
    @Scheduled(fixedDelay = 600_000)
    public void cleanupExpiredSessions() {
        Instant cutoff = Instant.now().minus(SESSION_TIMEOUT_MINUTES, ChronoUnit.MINUTES);
        int before = sessions.size();
        sessions.entrySet().removeIf(e -> e.getValue().getLastActivity().isBefore(cutoff));
        int removed = before - sessions.size();
        if (removed > 0) {
            log.info("Cleaned up {} expired sessions, {} active", removed, sessions.size());
        }
    }
}
