import { ManualPageClient } from "@/components/ManualPageClient";
import { ProgressSteps } from "@/components/ProgressSteps";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Startup manual",
  description: "Beginner-friendly restaurant startup playbook generated by mock multi-agent pipeline.",
};

export default function ManualPage() {
  return (
    <div className="mx-auto w-full max-w-5xl px-4 py-10 sm:px-6">
      <div className="mx-auto max-w-3xl">
        <ProgressSteps active={3} />
      </div>
      <div className="mt-10">
        <ManualPageClient />
      </div>
    </div>
  );
}
